Check version numpy

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


**Membuat NumPy array**

Membuat numpy array baru 1D

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
#cek tipe data
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Melihat shape atau bentuk dari numpy array

In [ ]:
arr.shape

(5,)

Membuat array 2D

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


Melihat bentuk/shape array 2D

In [ ]:
arr.shape
#Angka pertama = member di sumbu 0 -> baris
#Angka kedua = member di sumbu 1 -> kolom

(2, 3)

Membuat array 3D

In [ ]:
arr = np.array([[[1,2,3], [4,5,6]],[[2,3,4], [5,6,7]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[2 3 4]
  [5 6 7]]]


Melihat bentuk shape array 3D

In [ ]:
arr.shape
#Angka pertama = member di sumbu 0
#Angka kedua = member di sumbu 1
#Angka ketiga = member di sumbu 2

(2, 2, 3)

Melihat dimensi

In [ ]:
print('jumlah dimensi adalah ' , arr.ndim)

jumlah dimensi adalah  3


Array dengan string sebagai member

In [ ]:
arr_str = np.array(['hello', 'nama', 'saya', 'rengganis'])
print(arr_str)

['hello' 'nama' 'saya' 'rengganis']


**Indexing dalam NumPy array**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2]) #menampilkan elemen ke 3
print(arr[0] + arr[2]) #hasil jumlah elemen

3
4


Mengakses elemen dalam 2D array

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Baris pertama, kolom kedua: ', arr[0,1])
print('Baris kedua, kolom ketiga: ',arr[1,2])

Baris pertama, kolom kesatu:  2
Baris kedua, kolom ketiga:  6


Menampilkan elemen di 3D array

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[10, 11, 12], [13, 14, 14]]])
print(arr)
print(arr[1, 0, 1])
print(arr[1, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 14]]]
11
14


contoh array 3d yang bentuknya sama dengan gambar 3d di slide materi

In [ ]:
arr_test = np.array([[[1, 2], [3, 4], [5, 6]],
[[10, 11], [12, 13], [14, 15]],
[[16, 17], [18, 19], [20, 21]],
[[22, 23], [24, 25], [26, 27]]])
print(arr_test)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]]

 [[22 23]
  [24 25]
  [26 27]]]


In [ ]:
print(arr_test.shape)

(4, 3, 2)


**NumPy Array Slicing**

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[1:4]) # menampilkan elemen index 1 sampai dengan index ke 4 (index 4 tidak masuk)
print(arr[:3]) # menampilkan elemen awal sampai 3 (index 3 tidak masuk)
print(arr[2:]) # menampilkan elemen 3 hingga akhir (index 2 termasuk)

[2 3 4]
[1 2 3]
[3 4 5]


Slicing 2D

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
# menampilkan angka 5 dan 6
#sumbu 0 : index 1
#sumbu 1 : index 1 sampai akhir
print(arr[1,1:])
# menampilkan angka 2 dan 5
#sumbu 0 : semua
#sumbu 1 : index 1
print(arr[:,1])

[5 6]
[2 5]


Slicing 3d

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[10, 11, 12], [13, 14, 15]]])
print(arr[1, 1, 1:])

[14 15]


**Mengonversi Tipe Data**

In [ ]:
arr = np.array(['1','2','3','4','5'])
newarr = arr.astype('i')
print(arr)
print(newarr)

['1' '2' '3' '4' '5']
[1 2 3 4 5]


Merubah string ke float

In [ ]:
arr = np.array(['1','2','3','4','5'])
newarr = arr.astype('f')
print(arr)
print(newarr)

['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]


Reshape

In [ ]:
# 1d ke 2d
# pastikan jumlah elemen nya cukup ketika dirubah ke bentuk lain
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
new_arr = arr.reshape(3,4)
# sumbu 0 : 3 member
# sumbu 1 : 4 member
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(new_arr.shape)

(3, 4)


2D ke 3D array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
print('')
new_arr = arr.reshape(2,3,2)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
print(new_arr.shape)

(2, 3, 2)


3D array ke 1 array

In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[10, 11, 12], [13, 14, 15]]])
print(arr)
print('sudah di reshape')
new_arr = arr.reshape(-1)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[10 11 12]
  [13 14 15]]]
sudah di reshape
[ 1  2  3  4  5  6 10 11 12 13 14 15]


Perbedaan len dan shape

In [ ]:
print(len(arr))
print(arr.shape)

2
(2, 2, 3)


Iteration

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in range(len(arr)):
  print(arr[i])

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for i in range(arr.shape[0]):
  print(arr[i])

1
2
3
4
5
6
7
8
9
10
11
12


Iterasi array 2D

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])
for i in arr:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
for i in range(len(arr)):
  for j in range(len(arr[i])):
    print(arr[i,j])

1
2
3
4
5
6


Iterasi array 3D

In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[10,11,12], [13,14,15]]])
for i in arr:
  for j in i:
    for z in j:
      print(z)
    print('')
  print('')

1
2
3

4
5
6


10
11
12

13
14
15




In [ ]:
arr = np.array([[[1,2,3], [4,5,6]], [[10,11,12], [13,14,15]]])
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    for z in range(arr.shape[2]):
      print(arr[i,j,z])
    print('')
  print('')

1
2
3

4
5
6


10
11
12

13
14
15




Join

In [ ]:
#sumbu 0 array 1D
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[1 2 3 4 5 6]


In [ ]:
#join array 2d
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[11,12,13], [14,15,16]])

print(arr1)
print('')
print(arr2)

[[1 2 3]
 [4 5 6]]

[[11 12 13]
 [14 15 16]]


In [ ]:
#kita menambah di sumbu 0
arr3 = np.concatenate((arr1, arr2), axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]


array split

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#dipisah menjadi 3 bagian array
new_arr = np.array_split(arr, 3)
print('sebelum')
print(arr)
print('sesudah')
print(new_arr)
narr = new_arr[2]
print('akses index 2')
print(narr)

sebelum
[ 1  2  3  4  5  6  7  8  9 10 11 12]
sesudah
[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]
akses index 2
[ 9 10 11 12]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#dipisah menjadi 5 bagian array
new_arr = np.array_split(arr, 5)
print('sebelum')
print(arr)
print('sesudah')
print(new_arr)
print('akses index 2')
narr = new_arr[2]
print(narr)

sebelum
[ 1  2  3  4  5  6  7  8  9 10 11 12]
sesudah
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10]), array([11, 12])]
akses index 2
[7 8]


In [ ]:
#array search
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#mencari elemen yg nilainya 3, dan mengembalikan indeksnya
x = np.where(arr==3)
print(x)

(array([2]),)


In [ ]:
#sorting
arr = np.array([11,21,3,4,19,21,1,12])
print(arr)

new_arr = np.sort(arr)
print(new_arr)

[11 21  3  4 19 21  1 12]
[ 1  3  4 11 12 19 21 21]


In [ ]:
#random
from numpy import random

x = random.rand(2)
print(x)

[0.05758638 0.60307109]


In [ ]:
#ufuncs
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
arr3 = np.add(arr1, arr2)
print(arr3)


[11 22 33 44 55]


In [ ]:
#summation
arr1 = np.array([1,2,3,4,5])
arr3 = np.sum(arr1)
print(arr3)

15


In [ ]:
#product of element
arr1 = np.array([1,2,3,4,5])
arr3 = np.prod(arr1)
print(arr3)

120
